// src/lib/components/Glyphs.svelte
<script lang="ts">
    import { appState, type Glyph } from '$lib/state.svelte';
    import { invoke } from '@tauri-apps/api/core';
    import { Plus, Trash2, Bot } from 'lucide-svelte';

    let selectedGlyphId = $state<string | null>(null);

    let activeGlyph = $derived.by(() => {
        if (!selectedGlyphId && appState.glyphs.length > 0) {
            return appState.glyphs[0];
        }
        return appState.glyphs.find(g => g.id === selectedGlyphId) || null;
    });

    // Form states
    let name = $state('');
    let model = $state('gemini-1.5-pro');
    let temperature = $state(0.7);
    let outputLength = $state(2048);
    let isSculpter = $state(false);
    let role = $state('');
    let specialistRole = $state('');

    // Sync form with active glyph only when the selected glyph changes
    let currentGlyphId = $state<string | null>(null);

    $effect(() => {
        const id = activeGlyph?.id || null;
        if (id !== currentGlyphId) {
            currentGlyphId = id;
            if (activeGlyph) {
                name = activeGlyph.name;
                model = activeGlyph.model;
                temperature = activeGlyph.temperature;
                outputLength = activeGlyph.outputLength;
                isSculpter = activeGlyph.isSculpter;
                role = activeGlyph.role;
                specialistRole = activeGlyph.specialistRole || '';
            } else {
                name = '';
                model = 'gemini-1.5-pro';
                temperature = 0.7;
                outputLength = 2048;
                isSculpter = false;
                role = '';
                specialistRole = '';
            }
        }
    });

    async function handleSave() {
        if (!activeGlyph) return;
        const updated: Glyph = {
            id: activeGlyph.id,
            name,
            model,
            temperature,
            outputLength,
            isSculpter,
            role,
            specialistRole: specialistRole || undefined
        };
        
        // Optimistically update local state so UI doesn't reset mid-typing
        const idx = appState.glyphs.findIndex(g => g.id === activeGlyph!.id);
        if (idx !== -1) {
            appState.glyphs[idx] = updated;
        }

        await invoke('save_glyph', { glyph: updated });
    }

    async function createNew() {
        const id = `glyph_${Date.now()}`;
        const newGlyph: Glyph = {
            id,
            name: 'New Glyph',
            model: 'gemini-1.5-pro',
            temperature: 0.7,
            outputLength: 2048,
            isSculpter: false,
            role: 'You are a helpful assistant.'
        };
        await invoke('save_glyph', { glyph: newGlyph });
        appState.glyphs = await invoke<Glyph[]>('list_glyphs') || [];
        selectedGlyphId = id;
    }

    async function handleDelete(id: string) {
        if (!confirm("Delete this Glyph?")) return;
        await invoke('delete_glyph', { id });
        appState.glyphs = await invoke<Glyph[]>('list_glyphs') || [];
        if (selectedGlyphId === id) selectedGlyphId = null;
    }
</script>

<div class="flex-1 flex flex-col h-full bg-[#050308] overflow-hidden">
    <!-- Header -->
    <div class="p-8 border-b border-violet-900/40 bg-[#020005]">
        <h1 class="text-3xl text-violet-100 font-bold font-heading uppercase tracking-widest flex items-center gap-4">
            <Bot size={32} class="text-violet-500" />
            Glyph Registry
        </h1>
        <p class="text-violet-400 mt-2 font-mono text-xs uppercase tracking-widest">
            Configure sculptors and chisels for carving your world.
        </p>
    </div>

    <div class="flex-1 flex min-h-0 divide-x divide-violet-900/40">
        <!-- Sidebar: List of Glyphs -->
        <div class="w-64 bg-[#020005] overflow-y-auto p-4 flex flex-col gap-2">
            <button 
                onclick={createNew}
                class="w-full py-2 px-3 flex items-center justify-center gap-2 border border-violet-500/40 text-violet-300 font-bold text-xs uppercase tracking-widest rounded-lg hover:bg-violet-900/30 hover:border-violet-500 transition-colors mb-4"
            >
                <Plus size={14} /> New Glyph
            </button>

            {#each appState.glyphs as glyph}
                <div 
                    class="w-full text-left group flex items-center justify-between px-3 py-2 border border-violet-700/30 bg-violet-950/20 rounded-lg cursor-pointer hover:bg-violet-900/30 transition-colors {activeGlyph?.id === glyph.id ? 'border-violet-500 bg-violet-900/40' : ''}" 
                    role="button"
                    tabindex="0"
                    onclick={() => selectedGlyphId = glyph.id}
                    onkeydown={(e) => { if (e.key === 'Enter') selectedGlyphId = glyph.id; }}
                >
                    <div class="flex items-center gap-2 font-mono text-xs text-violet-100 truncate">
                        <Bot size={12} class="text-violet-500" />
                        <span class="truncate">{glyph.name}</span>
                        {#if glyph.specialistRole && !glyph.isSculpter}
                            <span class="px-1.5 py-0.5 rounded border border-violet-500/50 bg-violet-500/20 text-violet-300 text-[9px] uppercase tracking-widest ml-2 flex-shrink-0">
                                {glyph.specialistRole}
                            </span>
                        {/if}
                    </div>
                    <button 
                        class="text-red-500/50 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center p-1"
                        onclick={(e) => { e.stopPropagation(); handleDelete(glyph.id); }}
                        aria-label="Delete Glyph"
                    >
                        <Trash2 size={12} />
                    </button>
                </div>
            {/each}
        </div>

        <!-- Editor Pane -->
        <div class="flex-1 overflow-y-auto p-8 font-mono text-sm text-violet-200">
            {#if activeGlyph}
                <div class="max-w-2xl mx-auto space-y-8">
                    <!-- Basic Info -->
                    <div class="grid grid-cols-2 gap-6">
                        <div class="space-y-2 col-span-2">
                            <label for="glyph-name" class="block text-[10px] uppercase tracking-widest text-violet-500 font-bold">Designation (Name)</label>
                            <input 
                                id="glyph-name"
                                type="text" 
                                bind:value={name}
                                oninput={handleSave}
                                class="w-full bg-[#020005] border border-violet-700/40 rounded-lg px-4 py-2 text-violet-100 outline-none focus:border-violet-500 focus:shadow-[0_0_15px_rgba(139,92,246,0.2)] transition-all"
                            />
                        </div>

                        <div class="space-y-2">
                            <label for="glyph-model" class="block text-[10px] uppercase tracking-widest text-violet-500 font-bold">Model Kernel</label>
                            <input 
                                id="glyph-model"
                                type="text"
                                bind:value={model}
                                oninput={handleSave}
                                placeholder="e.g. gemini-1.5-pro"
                                class="w-full bg-[#020005] border border-violet-700/40 rounded-lg px-4 py-2 text-violet-100 outline-none focus:border-violet-500 transition-all"
                            />
                        </div>

                        <div class="space-y-2">
                            <label for="glyph-temp" class="block text-[10px] uppercase tracking-widest text-violet-500 font-bold flex justify-between">
                                <span>Temperature</span>
                                <span>{temperature.toFixed(2)}</span>
                            </label>
                            <input 
                                id="glyph-temp"
                                type="range" 
                                min="0" max="2" step="0.05"
                                bind:value={temperature}
                                onchange={handleSave}
                                class="w-full accent-violet-500"
                            />
                        </div>

                        <div class="space-y-2">
                            <label for="glyph-tokens" class="block text-[10px] uppercase tracking-widest text-violet-500 font-bold flex justify-between items-center">
                                <span>Output Length (Tokens)</span>
                                <input 
                                    type="number"
                                    bind:value={outputLength}
                                    oninput={handleSave}
                                    class="bg-transparent border-b border-violet-900/60 w-16 text-right outline-none focus:border-violet-500 text-violet-100"
                                />
                            </label>
                            <input 
                                id="glyph-tokens"
                                type="range" 
                                min="256" max="8192" step="256"
                                bind:value={outputLength}
                                onchange={handleSave}
                                class="w-full accent-violet-500"
                            />
                        </div>

                        <div class="space-y-2 flex items-center pt-6">
                            <label class="flex items-center gap-3 cursor-pointer group">
                                <input 
                                    type="checkbox"
                                    bind:checked={isSculpter}
                                    onchange={handleSave}
                                    class="w-4 h-4 bg-[#020005] border border-violet-900 rounded checked:bg-violet-500 appearance-none flex items-center justify-center after:content-[''] after:w-2 after:h-2 after:bg-white after:rounded-sm after:hidden checked:after:block outline-none"
                                />
                                <span class="text-xs uppercase tracking-widest text-violet-300 group-hover:text-violet-100 transition-colors">Sculptor (Show in Studio)</span>
                            </label>
                        </div>

                        {#if !isSculpter}
                        <div class="space-y-2 col-span-2 border-t border-violet-900/40 pt-4 mt-2">
                            <label for="glyph-specialist-role" class="block text-[10px] uppercase tracking-widest text-violet-500 font-bold">Chisel Tag</label>
                            <div class="flex gap-4 items-center">
                                <select 
                                    id="glyph-specialist-role"
                                    bind:value={specialistRole}
                                    onchange={handleSave}
                                    class="flex-1 bg-[#020005] border border-violet-700/40 rounded-lg px-4 py-2 text-violet-100 outline-none focus:border-violet-500 transition-all font-mono text-xs appearance-none"
                                >
                                    <option value="">-- None --</option>
                                    <option value="researcher">Researcher</option>
                                    <option value="writer">Writer</option>
                                    <option value="auditor">Auditor</option>
                                    <option value="architect">Architect</option>
                                    <option value="analyst">Analyst</option>
                                </select>
                                <div class="text-[9px] text-violet-400/80 w-1/2 leading-relaxed">
                                    Sculptors delegate work to chisels tagged with the required <span class="text-violet-300">researcher</span>, <span class="text-violet-300">writer</span>, or <span class="text-violet-300">auditor</span> role during multi-step carving sessions.
                                </div>
                            </div>
                        </div>
                        {/if}
                    </div>

                    <!-- Role / Prompt -->
                    <div class="space-y-2">
                        <label for="glyph-role" class="block text-[10px] uppercase tracking-widest text-violet-500 font-bold">Chisel Role (System Prompt)</label>
                        <textarea 
                            id="glyph-role"
                            bind:value={role}
                            oninput={handleSave}
                            rows="10"
                            class="w-full bg-[#020005] border border-violet-700/40 rounded-lg px-4 py-3 text-violet-100 outline-none focus:border-violet-500 focus:shadow-[0_0_15px_rgba(139,92,246,0.2)] transition-all resize-none leading-relaxed"
                            placeholder="You are a chisel specializing in..."
                        ></textarea>
                    </div>

                </div>
            {:else}
                <div class="h-full flex flex-col items-center justify-center opacity-50 space-y-4">
                    <Bot size={48} class="text-violet-700" />
                    <p class="uppercase tracking-widest text-xs">No Glyph Selected</p>
                </div>
            {/if}
        </div>
    </div>
</div>

// src/app/glyphs/page.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Glyph = {
  id: string;
  name: string;
  systemInstruction: string;
  provider: "gemini" | "openai" | "anthropic";
  model: string;
  temperature: number;
  maxOutputTokens: number;
  isSculpter?: boolean;
  specialistRole?: string;
};

export default function GlyphsPage() {
  const [glyphs, setGlyphs] = useState<Glyph[]>([]);
  const [editing, setEditing] = useState<Glyph | null>(null);
  const [availableProviders, setAvailableProviders] = useState<string[]>(["gemini"]);

  useEffect(() => {
    fetch("/api/glyphs").then((r) => r.json()).then(setGlyphs).catch(() => {});
    fetch("/api/providers").then((r) => r.json()).then((d) => setAvailableProviders(d.providers ?? ["gemini"])).catch(() => {});
  }, []);

  async function handleSave(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const isSculpterRaw = fd.get("isSculpter");
    const payload = {
      name: fd.get("name") as string,
      systemInstruction: fd.get("systemInstruction") as string,
      provider: fd.get("provider") as string || "gemini",
      model: fd.get("model") as string,
      temperature: parseFloat(fd.get("temperature") as string) || 0.7,
      maxOutputTokens: parseInt(fd.get("maxOutputTokens") as string, 10) || 2048,
      isSculpter: isSculpterRaw === "on" || isSculpterRaw === "true",
      specialistRole: (fd.get("specialistRole") as string) || undefined,
    };

    if (editing) {
      const res = await fetch(`/api/glyphs/${editing.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (res.ok) {
        const updated = await res.json();
        setGlyphs((prev) => prev.map((g) => (g.id === updated.id ? updated : g)));
        setEditing(null);
      }
    } else {
      const res = await fetch("/api/glyphs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (res.ok) {
        const created = await res.json();
        setGlyphs((prev) => [created, ...prev]);
      }
    }
  }

  async function handleDelete(id: string) {
    if (!confirm("Delete this Glyph?")) return;
    const res = await fetch(`/api/glyphs/${id}`, { method: "DELETE" });
    if (res.ok) {
      setGlyphs((prev) => prev.filter((g) => g.id !== id));
      if (editing?.id === id) setEditing(null);
    }
  }

  return (
    <div className="flex h-screen w-full flex-col font-sans text-violet-300">
      {/* Top Header */}
      <header className="flex shrink-0 items-center justify-between border-b border-violet-500/60 bg-[#020005] px-4 py-2 text-[10px] font-bold uppercase tracking-[0.2em] text-violet-400 shadow-[0_0_15px_rgba(139,92,246,0.15)] relative z-10">
        <div className="flex items-center gap-6 z-10">
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-violet-500 animate-pulse"></span>
            <span className="font-heading text-lg tracking-[0.3em] text-violet-200 [text-shadow:0_0_10px_rgba(167,139,250,0.8)]">
              RHYOLITE//
            </span>
          </div>
          <div className="hidden sm:flex flex-col border-l border-violet-800/60 pl-4">
            <span className="text-[8px] text-violet-600 tracking-[0.3em]">SYS.MODULE</span>
            <span className="text-violet-300 font-mono tracking-widest text-[11px]">GLYPH_CONFIG</span>
          </div>
        </div>
        <div className="flex items-center gap-6 z-10">
          <Link
            href="/workspace"
            className="border border-violet-500/60 bg-violet-950/80 px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-violet-200 hover:border-violet-400 hover:bg-violet-900/60 transition-colors"
          >
            [ ← RETURN_TO_WORKSPACE ]
          </Link>
        </div>
      </header>

      <div className="flex-1 overflow-y-auto bg-[#050308] relative">
        <div className="mx-auto max-w-4xl border-x border-violet-500/50 px-4 py-6 md:px-6 min-h-full">
          <div className="mb-6 flex flex-col gap-1 border-b border-violet-600/50 pb-4">
            <h1 className="font-heading text-2xl font-bold tracking-[0.2em] text-violet-100 [text-shadow:0_0_14px_rgba(167,139,250,0.8)] uppercase">
              Glyph_Registry
            </h1>
            <p className="mt-1 text-[10px] uppercase tracking-[0.3em] text-violet-500 font-mono">
              Persona & model profiles
            </p>
          </div>

          <div className="grid gap-0 border border-violet-500/50 md:grid-cols-2 md:divide-x md:divide-violet-500/50 font-mono">
            <div className="border-b border-violet-500/50 p-4 md:border-b-0 md:p-5">
              <h2 className="mb-4 text-[10px] font-bold uppercase tracking-[0.2em] text-violet-500 font-mono">
                {editing ? "[ EDIT_GLYPH ]" : "[ NEW_GLYPH ]"}
              </h2>
          <form onSubmit={handleSave} className="flex flex-col gap-4 font-mono">
            <div className="relative border border-violet-700/50 bg-[#020005] p-3">
              <div className="absolute top-0 left-0 w-1.5 h-1.5 border-t border-l border-violet-500"></div>
              <div className="absolute top-0 right-0 w-1.5 h-1.5 border-t border-r border-violet-500"></div>
              <div className="absolute bottom-0 left-0 w-1.5 h-1.5 border-b border-l border-violet-500"></div>
              <div className="absolute bottom-0 right-0 w-1.5 h-1.5 border-b border-r border-violet-500"></div>
              
              <div className="flex flex-col gap-4">
                <div>
                  <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                    &gt; Name
                  </label>
                  <input
                    key={`name-${editing?.id || "new"}`}
                    name="name"
                    defaultValue={editing?.name}
                    required
                    className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                    &gt; Provider
                  </label>
                  <select
                    key={`provider-${editing?.id || "new"}`}
                    name="provider"
                    defaultValue={editing?.provider || "gemini"}
                    className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow"
                  >
                    {availableProviders.map((p) => (
                      <option key={p} value={p} className="bg-black">{p.toUpperCase()}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                    &gt; Model
                  </label>
                  <input
                    key={`model-${editing?.id || "new"}`}
                    name="model"
                    defaultValue={editing?.model || "gemini-3.1-pro-preview"}
                    required
                    className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow"
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                      &gt; Temp
                    </label>
                    <input
                      key={`temp-${editing?.id || "new"}`}
                      name="temperature"
                      type="number"
                      step="0.1"
                      min="0"
                      max="2"
                      defaultValue={editing?.temperature ?? 0.7}
                      className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow"
                    />
                  </div>
                  <div>
                    <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                      &gt; Max tok
                    </label>
                    <input
                      key={`tokens-${editing?.id || "new"}`}
                      name="maxOutputTokens"
                      type="number"
                      defaultValue={editing?.maxOutputTokens ?? 2048}
                      className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow"
                    />
                  </div>
                </div>
                <div>
                  <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                    &gt; System instruction
                  </label>
                  <textarea
                    key={`instructions-${editing?.id || "new"}`}
                    name="systemInstruction"
                    defaultValue={editing?.systemInstruction}
                    rows={5}
                    className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow"
                  />
                </div>
                <div className="border-t border-violet-800/40 pt-3 mt-1 flex flex-col gap-3">
                  <label className="flex items-center gap-3 cursor-pointer group/toggle">
                    <input
                      key={`sculpter-${editing?.id || "new"}`}
                      type="checkbox"
                      name="isSculpter"
                      defaultChecked={editing ? editing.isSculpter !== false : true}
                      className="accent-violet-500 h-4 w-4"
                    />
                    <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-violet-500 group-hover/toggle:text-violet-300 transition-colors">
                      Sculpter (show in comms)
                    </span>
                  </label>
                  <p className="text-[9px] uppercase tracking-widest text-violet-700 -mt-1 pl-7">
                    Uncheck to make this a specialist — a sub-agent template invoked via delegation only.
                    Dead link resolver uses: <span className="text-cyan-700">researcher</span>, <span className="text-cyan-700">writer</span>, <span className="text-cyan-700">auditor</span>
                  </p>
                  <div>
                    <label className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600">
                      &gt; Specialist role tag
                    </label>
                    <input
                      key={`role-${editing?.id || "new"}`}
                      name="specialistRole"
                      defaultValue={editing?.specialistRole}
                      placeholder="e.g. researcher, writer, auditor"
                      className="w-full border border-violet-700/50 bg-black px-3 py-2 text-sm text-violet-100 outline-none focus:border-violet-400 focus:shadow-uv-glow placeholder:text-violet-800"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-1 flex flex-wrap gap-2">
              <button
                type="submit"
                className="border border-violet-500/70 bg-violet-950/80 px-4 py-2 text-[10px] font-bold uppercase tracking-widest text-violet-100 hover:border-violet-400 hover:bg-violet-900/60 transition-colors"
              >
                [ {editing ? "UPDATE_GLYPH" : "CREATE_GLYPH"} ]
              </button>
              {editing && (
                <button
                  type="button"
                  onClick={() => setEditing(null)}
                  className="border border-violet-800/80 bg-black px-4 py-2 text-[10px] font-bold uppercase tracking-[0.2em] text-violet-500 hover:border-violet-600 hover:bg-violet-950/30 transition-colors"
                >
                  [ CANCEL ]
                </button>
              )}
            </div>
          </form>
        </div>

        <div className="flex flex-col">
          {glyphs.map((g) => (
            <div
              key={g.id}
              className="group flex flex-col gap-2 border-b border-violet-500/50 p-4 last:border-b-0 hover:bg-violet-950/20 transition-colors"
            >
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-violet-500 opacity-50 font-bold">&gt;</span>
                  <h3 className="font-heading text-base font-bold text-violet-100 uppercase tracking-wider">{g.name}</h3>
                  <span className={`text-[8px] font-bold uppercase tracking-widest px-1.5 py-0.5 border ${g.isSculpter === false ? "border-cyan-700/60 text-cyan-500 bg-cyan-950/30" : "border-violet-700/60 text-violet-400 bg-violet-950/30"}`}>
                    {g.isSculpter === false ? "SPECIALIST" : "SCULPTER"}
                  </span>
                  {g.specialistRole && (
                    <span className="text-[8px] font-bold uppercase tracking-widest text-violet-600">
                      [{g.specialistRole}]
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button
                    type="button"
                    onClick={() => setEditing(g)}
                    className="text-[10px] font-bold uppercase tracking-[0.2em] text-violet-400 hover:text-violet-200"
                  >
                    [EDIT]
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDelete(g.id)}
                    className="text-[10px] font-bold uppercase tracking-[0.2em] text-red-500/90 hover:text-red-400"
                  >
                    [DEL]
                  </button>
                </div>
              </div>
              <div className="text-[10px] uppercase tracking-widest text-violet-600 pl-4 border-l border-violet-800/50 ml-1">
                {(g.provider || "gemini").toUpperCase()}:{g.model} · TEMP:{g.temperature}
              </div>
              <div className="line-clamp-2 text-xs text-violet-500/80 pl-4 border-l border-violet-800/50 ml-1 mt-1">
                {g.systemInstruction || "—"}
              </div>
            </div>
          ))}
          {glyphs.length === 0 && (
            <div className="p-4 text-xs font-bold uppercase tracking-[0.2em] text-violet-800 animate-pulse">
              [ NO_GLYPHS_FOUND ]
            </div>
          )}
        </div>
      </div>
    </div>
  </div>
      
  {/* Footer System Bar */}
      <footer className="shrink-0 flex items-center justify-between border-t border-violet-500/60 bg-[#020005] px-4 py-1.5 text-[10px] uppercase tracking-widest text-violet-600 font-mono shadow-[0_0_15px_rgba(139,92,246,0.15)] relative z-10">
        <div className="flex gap-4">
          <span>SYS_MEM: <span className="text-violet-400">ALLOCATED</span></span>
          <span className="hidden sm:inline">REGISTRY: <span className="text-violet-400">{glyphs.length} ACTIVE</span></span>
        </div>
        <div className="flex gap-4 items-center">
          <span className="hidden sm:inline opacity-50">NODE_LOCAL</span>
          <span className="text-violet-400 font-bold animate-pulse">■</span>
        </div>
      </footer>
    </div>
  );
}
